Update config ymls for new software-bootstrap architecture
Change-Id: I58fcc20d92c7a1b8f4eb43fec9de4b1ff9fd413e

diff --git a/configs/private-compute-cloud.yml b/configs/private-compute-cloud.yml
--- a/configs/private-compute-cloud.yml
+++ b/configs/private-compute-cloud.yml
@@ -19,7 +19,7 @@
 # This file describes the configuration for a private compute cloud.
 # It features three controller nodes, compute nodes, and Ceph OSD nodes.
 
-version: 1.0
+version: 1.1
 
 reference-architecture:
     - private-compute-cloud
@@ -56,12 +56,10 @@ networks:
         dns-search: mycompany.domain.com
         method: static
         eth-port: eth10
-        mtu: 9000
     external2:
         description: Interface for eth11
         method: manual
         eth-port: eth11
-        mtu: 9000
     pxe-dhcp:
         description: Change pxe port(eth15) to dhcp
         method: dhcp
@@ -74,7 +72,6 @@ networks:
         addr: 172.29.236.0/22
         vlan: 10
         eth-port: eth10
-        mtu: 9000
     openstack-stg:
         description: OpenStack Storage Network
         bridge: br-storage
@@ -83,7 +80,6 @@ networks:
         addr: 172.29.244.0/22
         vlan: 20
         eth-port: eth10
-        mtu: 9000
     openstack-tenant-vxlan:
         description: OpenStack Tenant vxlan Network
         bridge: br-vxlan
@@ -105,7 +101,6 @@ networks:
         method: static
         vlan: 40
         eth-port: eth11
-        mtu: 9000
 racks:
     - rack-id: rack1
       data-center: dataeast
@@ -252,33 +247,36 @@ node-templates:
             - /dev/sdg
             - /dev/sdh
 
-software-bootstrap-hosts: controllers[0]  # Select first 'controllers' node
-software-bootstrap-cmd: |
-    set -o pipefail
-    apt-get -y update >/dev/null 2>&1
-    type git >/dev/null 2>&1
-    if [ $? != 0 ]; then
-        apt-get install -qq -y git
-    fi
-    if [ ! -d os-services ]; then
-        git clone git://github.com/open-power-ref-design/os-services.git
-    fi
-    cd os-services
-#    git checkout v1.3.0
-    export DEPLOY_CEPH=yes
-    export DEPLOY_OPSMGR=yes
-    # export ANSIBLE_HOST_KEY_CHECKING=False
-    ./scripts/bootstrap-cluster.sh | tee -a ../bootstrap-cluster.out
-    rc=$?
-    if [ $rc != 0 ]; then
-        echo "./scripts/bootstrap-cluster.sh failed, rc=$rc"
-        exit $rc
-    fi
-    HOST=`hostname -A`
-    echo ""
-    echo "The deployment should now be continued on the first controller node"
-    echo "Please log into $HOST and complete the installation"
-    echo ""
-    echo "ssh ubuntu@$HOST"
-    echo "sudo su"
-    echo "cd ~/os-services"
+software-bootstrap:
+    controllers[0]: |
+        /bin/bash -c '
+        set -o pipefail
+        apt-get -y update >/dev/null 2>&1
+        type git >/dev/null 2>&1
+        if [ $? != 0 ]; then
+            apt-get install -qq -y git
+        fi
+        if [ ! -d os-services ]; then
+            git clone git://github.com/open-power-ref-design/os-services.git
+        fi
+        cd os-services
+        # git checkout v1.3.0
+        export DEPLOY_CEPH=yes
+        export DEPLOY_OPSMGR=yes
+        # export ANSIBLE_HOST_KEY_CHECKING=False
+        ./scripts/bootstrap-cluster.sh | tee -a ../bootstrap-cluster.out
+        rc=$?
+        if [ $rc != 0 ]; then
+            echo "./scripts/bootstrap-cluster.sh failed, rc=$rc"
+            exit $rc
+        fi
+        HOST=`hostname -A`
+        echo ""
+        echo "The deployment should now be continued on the first controller node"
+        echo "Please log into $HOST and complete the installation"
+        echo ""
+        echo "ssh ubuntu@$HOST"
+        echo "sudo su"
+        echo "cd ~/os-services"
+        '
+
diff --git a/configs/swift-medium.yml b/configs/swift-medium.yml
--- a/configs/swift-medium.yml
+++ b/configs/swift-medium.yml
@@ -23,7 +23,7 @@
 # It features three controller nodes, Swift proxy nodes,
 # Swift object nodes.
 
-version: 1.0
+version: 1.1
 
 reference-architecture:
     - swift
@@ -242,33 +242,36 @@ node-templates:
             - openstack-stg
             - swift-replication
 
-software-bootstrap-hosts: controllers[0]  # Select first 'controllers' node
-software-bootstrap-cmd: |
-    set -o pipefail
-    apt-get -y update >/dev/null 2>&1
-    type git >/dev/null 2>&1
-    if [ $? != 0 ]; then
-        apt-get install -qq -y git
-    fi
-    if [ ! -d os-services ]; then
-        git clone git://github.com/open-power-ref-design/os-services.git
-    fi
-    cd os-services
-#    git checkout v1.3.0
-    export DEPLOY_CEPH=no
-    export DEPLOY_OPSMGR=yes
-    # export ANSIBLE_HOST_KEY_CHECKING=False
-    ./scripts/bootstrap-cluster.sh | tee -a ../bootstrap-cluster.out
-    rc=$?
-    if [ $rc != 0 ]; then
-        echo "./scripts/bootstrap-cluster.sh failed, rc=$rc"
-        exit $rc
-    fi
-    HOST=`hostname -A`
-    echo ""
-    echo "The deployment should now be continued on the first controller node"
-    echo "Please log into $HOST and complete the installation"
-    echo ""
-    echo "ssh ubuntu@$HOST"
-    echo "sudo su"
-    echo "cd ~/os-services"
+software-bootstrap:
+    controllers[0]: |
+        /bin/bash -c '
+        set -o pipefail
+        apt-get -y update >/dev/null 2>&1
+        type git >/dev/null 2>&1
+        if [ $? != 0 ]; then
+            apt-get install -qq -y git
+        fi
+        if [ ! -d os-services ]; then
+            git clone git://github.com/open-power-ref-design/os-services.git
+        fi
+        cd os-services
+        # git checkout v1.3.0
+        export DEPLOY_CEPH=no
+        export DEPLOY_OPSMGR=yes
+        # export ANSIBLE_HOST_KEY_CHECKING=False
+        ./scripts/bootstrap-cluster.sh | tee -a ../bootstrap-cluster.out
+        rc=$?
+        if [ $rc != 0 ]; then
+            echo "./scripts/bootstrap-cluster.sh failed, rc=$rc"
+            exit $rc
+        fi
+        HOST=`hostname -A`
+        echo ""
+        echo "The deployment should now be continued on the first controller node"
+        echo "Please log into $HOST and complete the installation"
+        echo ""
+        echo "ssh ubuntu@$HOST"
+        echo "sudo su"
+        echo "cd ~/os-services"
+        '
+
diff --git a/configs/swift-small-with-compute-cloud.yml b/configs/swift-small-with-compute-cloud.yml
--- a/configs/swift-small-with-compute-cloud.yml
+++ b/configs/swift-small-with-compute-cloud.yml
@@ -23,7 +23,7 @@
 # nodes, and the account, container, and object rings converged on the same
 # set of nodes.
 
-version: 1.0
+version: 1.1
 
 reference-architecture:
     - private-compute-cloud
@@ -97,6 +97,7 @@ networks:
         addr: 172.29.240.0/22
         vlan: 30
         eth-port: eth11
+        mtu: 9000
     openstack-tenant-vlan:
         description: OpenStack Tenant vlan Network
         bridge: br-vlan
@@ -104,6 +105,7 @@ networks:
         addr: 0.0.0.0/1  # Nodes do not get IPs assigned in this network
         eth-port: eth11
         bridge-port: veth12
+        mtu: 9000
     ceph-replication:
         description: Ceph Replication Network
         addr: 172.29.248.0/22
@@ -321,33 +323,36 @@ node-templates:
             - openstack-stg
             - swift-replication
 
-software-bootstrap-hosts: controllers[0]  # Select first 'controllers' node
-software-bootstrap-cmd: |
-    set -o pipefail
-    apt-get -y update >/dev/null 2>&1
-    type git >/dev/null 2>&1
-    if [ $? != 0 ]; then
-        apt-get install -qq -y git
-    fi
-    if [ ! -d os-services ]; then
-        git clone git://github.com/open-power-ref-design/os-services.git
-    fi
-    cd os-services
-#    git checkout v1.3.0
-    export DEPLOY_CEPH=yes
-    export DEPLOY_OPSMGR=yes
-    # export ANSIBLE_HOST_KEY_CHECKING=False
-    ./scripts/bootstrap-cluster.sh | tee -a ../bootstrap-cluster.out
-    rc=$?
-    if [ $rc != 0 ]; then
-        echo "./scripts/bootstrap-cluster.sh failed, rc=$rc"
-        exit $rc
-    fi
-    HOST=`hostname -A`
-    echo ""
-    echo "The deployment should now be continued on the first controller node"
-    echo "Please log into $HOST and complete the installation"
-    echo ""
-    echo "ssh ubuntu@$HOST"
-    echo "sudo su"
-    echo "cd ~/os-services"
+software-bootstrap:
+    controllers[0]: |
+        /bin/bash -c '
+        set -o pipefail
+        apt-get -y update >/dev/null 2>&1
+        type git >/dev/null 2>&1
+        if [ $? != 0 ]; then
+            apt-get install -qq -y git
+        fi
+        if [ ! -d os-services ]; then
+            git clone git://github.com/open-power-ref-design/os-services.git
+        fi
+        cd os-services
+        # git checkout v1.3.0
+        export DEPLOY_CEPH=yes
+        export DEPLOY_OPSMGR=yes
+        # export ANSIBLE_HOST_KEY_CHECKING=False
+        ./scripts/bootstrap-cluster.sh | tee -a ../bootstrap-cluster.out
+        rc=$?
+        if [ $rc != 0 ]; then
+            echo "./scripts/bootstrap-cluster.sh failed, rc=$rc"
+            exit $rc
+        fi
+        HOST=`hostname -A`
+        echo ""
+        echo "The deployment should now be continued on the first controller node"
+        echo "Please log into $HOST and complete the installation"
+        echo ""
+        echo "ssh ubuntu@$HOST"
+        echo "sudo su"
+        echo "cd ~/os-services"
+        '
+
